services:
  postgres:
    image: postgres:17-alpine
    container_name: agendamento-banco
    environment:
      POSTGRES_DB: agenda_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
